# 服务配置
server:
  port: 8081

# mybatis配置
mybatis:
  # 实体别名包设置
  type-aliases-package: com.miracle.api.entity
  # Mapper 文件路径配置
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    # 驼峰式命名
    map-underscore-to-camel-case: true
    # 自动生成主键
    use-generated-keys: true
    # 默认执行器：REUSE 执行器会重用预处理语句（PreparedStatement）
    default-executor-type: reuse
    # 语句执行超时时间，单位秒
    default-statement-timeout: 30
    # 为驱动的结果集获取数量（fetchSize）设置一个建议值
    default-fetch-size: 100
    # 当返回行的所有列都是空时，返回 null
    return-instance-for-empty-row: false
    # 开启缓存
    cache-enabled: true

# spring配置
spring:
  # 设置应用名
  application:
    name: spring-cloud-service-provider
  # 数据源配置
  datasource:
    url: jdbc:mysql://112.74.184.184:3306/cloud_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: miracle@123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource


